version: '3.1'

services:
  postgres:
    image: postgres
    container_name: auth-server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_server
    networks:
      - auth-server-net
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    container_name: auth-server-backend
    image: alkorovko/auth-server-backend:latest

    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: unless-stopped

networks:
  auth-server-net:
    driver: bridge