server:
  port: 8080

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_server
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  liquibase:
    change-log: classpath:db/changelog.yml
  sql:
    init:
      platform: postgresql
app:
  security:
    jwtSecret: JDJhJDA4JGpUdXQ2eGdZTzE1RFpGU0lkMGpkYWVsZEtGdDhXSjh6YTRXbVptVjVVNjFCRkhXc0Q0em1X
    jwtTimeToLive: ${JWT_TIME_TO_LIVE:60}